[package]
authors = ['Cdot Network <hello@cdot.network>']
description = 'An IBC implementation on Substrate.'
edition = '2018'
homepage = 'https://cdot.network'
license = 'Apache-2.0'
name = 'pallet-ibc'
repository = 'https://github.com/cdot-network/substrate-ibc/'
version = '2.0.0-pre.2'
documentation = "https://docs.rs/pallet-ibc"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# # alias "parity-scale-code" to "codec"
# [dependencies.codec]
# default-features = false
# features = ['derive']
# package = 'parity-scale-codec'
# version = '1.3.4'

[dependencies.finality-grandpa]
default-features = false
features = ['derive-codec']
version = '0.13.0'

[dependencies.hash-db]
default-features = false
version = '0.15.2'

[dependencies.serde]
default-features = false
optional = true
version = '1.0.101'

[dependencies.ibc]
version = "0.4.0"
default-features = false

[dependencies.tendermint-proto]
version = "0.19.0"

[dependencies]
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive', 'full'] }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-finality-grandpa = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }
sp-trie = { default-features = false, version = '3.0.0' }
prost = "0.7.0"
prost-types = "0.7.0"

[dev-dependencies]
hex = '0.4.0'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'finality-grandpa/std',
    'hash-db/std',
    'serde',
    'sp-core/std',
    'sp-finality-grandpa/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-trie/std',
]

[patch.crates-io]
ibc = { git = "https://github.com/DaviRain-Su/ibc-rs.git", branch =  "soares/flex-error" }
tendermint              = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
#tendermint-rpc          = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error"}
tendermint-proto        = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error"}
#tendermint-light-client = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error"}
#tendermint-testgen      = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error"}
ics23 = { git = "https://github.com/DaviRain-Su/ics23.git", branch = "suooprt-no-std" }
