[package]
authors = ['Cdot Network <hello@cdot.network>']
description = 'An IBC implementation on Substrate.'
edition = '2018'
homepage = 'https://cdot.network'
license = 'Apache-2.0'
name = 'pallet-ibc'
repository = 'https://github.com/cdot-network/substrate-ibc/'
version = '2.0.0-pre.2'
documentation = "https://docs.rs/pallet-ibc"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
finality-grandpa = { version = "0.13.0", default-features = false, features = ['derive-codec'] }
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive', 'full'] }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = '3.0.0', default-features = false }
sp-core = { version = '3.0.0', default-features = false }
sp-io = { version = '3.0.0', default-features = false }
sp-runtime = { version = '3.0.0', default-features = false }
sp-finality-grandpa = { version = '3.0.0', default-features = false }
sp-std = { version = '3.0.0', default-features = false }
sp-trie = { version = '3.0.0', default-features = false }
hash-db = { version = '0.15.2', default-features = false }
serde = { version = '1.0.101', default-features = false, optional = true }
ibc = { version = "0.4.0", default-features = false }
tendermint-proto = {version = "0.19.0" }
prost = "0.7.0"
prost-types = "0.7.0"

[dev-dependencies]
hex = '0.4.0'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'finality-grandpa/std',
    'hash-db/std',
    'serde',
    'sp-core/std',
    'sp-finality-grandpa/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-trie/std',
    'ibc/std',
]

[patch.crates-io]
ibc              = { git = "https://github.com/DaviRain-Su/ibc-rs.git", branch =  "soares/flex-error" }
tendermint       = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
tendermint-proto = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error"}
ics23            = { git = "https://github.com/DaviRain-Su/ics23.git", branch = "suooprt-no-std" }
